name: Check formatting and run tests
on:
  push:
    branches: [ "**" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  check_formatting_and_run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: rustfmt --check $(find . -name '*.rs')
    - uses: cachix/install-nix-action@v17
    - name: Run tests
      run: nix develop -c sh -c 'cargo test --workspace && (cd parsnips-emu && wasm-pack test --node --mode no-install)'
