name: Check formatting and run tests
on:
  push:
    branches: [ "**" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  check_formatting_and_run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ./target
    - name: Cache nix
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock') }}
        path: |
          /nix/store/
          /nix/var/nix/profiles/per-user/${{ env.USER }}/profile/bin
          /nix/var/nix/profiles/default/bin/
          /nix/var/nix/profiles/per-user/root/channel
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node_modules-${{ hashFiles('./parsnips-web/pnpm-lock.yaml') }}
        path: ./parsnips-web/node_modules
    - uses: cachix/install-nix-action@v17
    - name: Check formatting and run tests
      run: nix develop .#ci -i -c sh -c 'rustfmt --check $(find . -name "*.rs") && cargo test --workspace && (cd parsnips-emu && wasm-pack test --node --mode no-install && wasm-pack build --target web --mode no-install) && (cd parsnips-web && prettier --check . && pnpm install && rm -rf node_modules/parsnips-emu && pnpm run build && pnpm run check)'
