name: Check formatting and run tests
on:
  push:
    branches: [ "**" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  check_formatting_and_run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ./target
    - name: Cache nix
      uses: mtoohey31/cache-flake-attr@7fd5333baacccb7498f460f34ce958ef60f17541
      with:
        key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './flake.nix') }}
        flake_paths: .#devShells.x86_64-linux.ci
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node_modules-${{ hashFiles('./parsnips-web/pnpm-lock.yaml') }}
        path: |
          ~/.pnpm-store
          ./parsnips-web/node_modules
    - name: Check formatting and run tests
      run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop .#ci -i -c make
