name: Check formatting and run tests
on:
  push:
    branches: [ "**" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  check_formatting_and_run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - name: Check formatting and run tests
      run: nix develop .#ci -i -c sh -c 'rustfmt --check $(find . -name "*.rs") && cargo test --workspace && (cd parsnips-emu && wasm-pack test --node --mode no-install && wasm-pack build --target web --mode no-install) && (cd parsnips-web && prettier --check . && pnpm install && rm -rf node_modules/parsnips-emu && pnpm run build && pnpm run check)'
